version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db_find_team
    ports:
      - "5431:5432"
    env_file:
      - .env


  redis:
    image: redis:latest
    container_name: redis_find_team
    env_file:
      - .env
    ports:
      - "6378:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: find_team
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
    command: sh -c "sleep 2; alembic upgrade head; uvicorn src.main:app --host 0.0.0.0 --port 8000"
