version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: find_team
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - TEST_DB_NAME=${TEST_DB_NAME}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - ALGORITHM=${ALGORITHM}
      - COOKIE_ACCESS_TOKEN_KEY=${COOKIE_ACCESS_TOKEN_KEY}
      - COOKIE_REFRESH_TOKEN_KEY=${COOKIE_REFRESH_TOKEN_KEY}
    ports:
      - '8080:8000'
    command: ["/find_team/docker/app.sh"]
    depends_on:
      - postgresql_db
      - redis

  postgresql_db:
    image: postgres:latest
    container_name: postgresql_db_find_team
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:latest
    container_name: redis_find_team
    ports:
      - "6378:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 3
