"""rename_columns

Revision ID: 2698cce1ca1e
Revises: a21e07dcf9d0
Create Date: 2024-03-13 19:48:24.724722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2698cce1ca1e"
down_revision: Union[str, None] = "a21e07dcf9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team", sa.Column("team_contacts", sa.String(), nullable=False)
    )
    op.add_column(
        "team", sa.Column("team_description", sa.String(), nullable=False)
    )
    op.add_column(
        "team", sa.Column("team_deadline_at", sa.DateTime(), nullable=False)
    )
    op.add_column("team", sa.Column("team_city", sa.String(), nullable=False))
    op.add_column("team", sa.Column("team_tags", sa.String(), nullable=True))
    op.drop_column("team", "contacts")
    op.drop_column("team", "deadline_at")
    op.drop_column("team", "city")
    op.drop_column("team", "description")
    op.drop_column("team", "tags")
    op.add_column(
        "user_profile", sa.Column("contacts", sa.String(), nullable=False)
    )
    op.add_column(
        "user_profile", sa.Column("description", sa.String(), nullable=False)
    )
    op.add_column(
        "user_profile",
        sa.Column("hobby", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "user_profile", sa.Column("city", sa.String(), nullable=True)
    )
    op.drop_column("user_profile", "my_contacts")
    op.drop_column("user_profile", "my_city")
    op.drop_column("user_profile", "my_hobby")
    op.drop_column("user_profile", "my_description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column(
            "my_description", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "my_hobby",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_profile",
        sa.Column("my_city", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_profile",
        sa.Column(
            "my_contacts", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user_profile", "city")
    op.drop_column("user_profile", "hobby")
    op.drop_column("user_profile", "description")
    op.drop_column("user_profile", "contacts")
    op.add_column(
        "team",
        sa.Column("tags", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "team",
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "team",
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "team",
        sa.Column(
            "deadline_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "team",
        sa.Column(
            "contacts", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("team", "team_tags")
    op.drop_column("team", "team_city")
    op.drop_column("team", "team_deadline_at")
    op.drop_column("team", "team_description")
    op.drop_column("team", "team_contacts")
    # ### end Alembic commands ###
