"""add_profile

Revision ID: a21e07dcf9d0
Revises: d7b8d98f3266
Create Date: 2024-03-11 20:16:34.630231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a21e07dcf9d0"
down_revision: Union[str, None] = "d7b8d98f3266"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("city", sa.String(), nullable=False))
    op.add_column(
        "user_profile", sa.Column("my_contacts", sa.String(), nullable=False)
    )
    op.add_column(
        "user_profile",
        sa.Column("my_description", sa.String(), nullable=False),
    )
    op.add_column(
        "user_profile",
        sa.Column("my_hobby", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "user_profile", sa.Column("my_city", sa.String(), nullable=True)
    )
    op.alter_column(
        "user_profile", "image_path", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profile",
        "image_path",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("user_profile", "my_city")
    op.drop_column("user_profile", "my_hobby")
    op.drop_column("user_profile", "my_description")
    op.drop_column("user_profile", "my_contacts")
    op.drop_column("team", "city")
    # ### end Alembic commands ###
